namespace Mawasem.Application.Features.PublicCatalog.Contracts.Responses;

public sealed record PublicProductDetailsResponse(
    int Id ,
    string Slug ,
    string NameEn ,
    string NameAr ,
    string DescriptionEn ,
    string DescriptionAr ,
    decimal OriginalPrice ,
    decimal CurrentPrice ,
    decimal DiscountPercentage ,
    bool IsFeatured ,
    bool IsInStock ,
    bool CanPurchase ,
    string? PrimaryImageUrl ,
    PublicBrandReferenceResponse Brand ,
    PublicSeasonReferenceResponse Season ,
    IReadOnlyList<PublicCategoryReferenceResponse> Categories ,
    IReadOnlyList<PublicCollectionReferenceResponse> Collections ,
    IReadOnlyList<PublicGradeReferenceResponse> Grades ,
    IReadOnlyList<PublicTagReferenceResponse> Tags ,
    IReadOnlyList<PublicProductSpecificationResponse> Specifications ,
    IReadOnlyList<PublicProductImageResponse> Images ,
    IReadOnlyList<PublicProductOptionResponse> Options ,
    IReadOnlyList<PublicProductVariantResponse> Variants ,
    decimal AverageRating ,
    int ReviewCount ,
    IReadOnlyList<PublicProductReviewResponse> Reviews );
